### ISSUE TITLE
Eventemitter could not be the return object of every method of class payworks

### ISSUE THREAD

**Issue by Cereceres** [4yopping/banorte-payworks#4]
I think the event should not be emitted in the return instance method because for the moment that are emitted is probable that there is not listeners, may be better that the event be emitted in the class @markotom

**Comment by markotom** [comment]
Yes, maybe we need to delete event emitters for each method to avoid a possible memory leak, but I think is not a good approach. We can use an event emitter to listen general events, because probably you need to have the same logic in all transactions types. For instance,

```js
let payworks = new Payworks({})

// Listen events
payworks.on('auth approved', function () {
  // logic
})

// Coroutines
payworks.auth({})
payworks.auth({})
payworks.auth({})
payworks.auth({})
```

As we discuss before, with this solution we can be able to create separate architectures. I mean, using middlewares invoking coroutines and, at the same time, implementing observer patterns.

**Comment by Cereceres** [comment]
Thank you!! this seems a good solution

**Comment by markotom** [comment]
We are already working on a new release without method events.
But, this issue is pending to close.

**Comment by markotom** [comment]
The pull request #5 has been merged.
